name: requester
description: Provides a middlware API for package:http
version: 0.0.2
homepage: https://github.com/johnpryan/requester
author: John Ryan <john.p.ryan4@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  http: ^0.11.3
